### ISSUE TITLE
I wonder if this framework supports Windows?

### ISSUE THREAD

**Issue by NeekHua** [openvinotoolkit/nncf_pytorch#101]
If inscribe

**Comment by vshampor** [comment]
Greetings, @NeekHua !

No support for Windows out-of-the-box yet - we never tried, though. Anyway, it shouldn't be impossible, if you manage to set up proper dependencies (CUDA, Python, MSVC build environment etc.) on Windows and are prepared to handle a couple of directory pathing non-portability issues in the current NNCF codebase.

**Comment by NeekHua** [comment]
Ok, thank you for your answer
