### ISSUE TITLE
How to cite your work?

### ISSUE THREAD

**Issue by yqtianust** [openvinotoolkit/nncf_pytorch#102]
Hi, 
do you have a publication or arxiv for NNCF? How should I cite your work properly?

**Comment by vshampor** [comment]
@AlexKoff88, do you have a BibTeX entry at hand? Should probably add this to the front page README as well

**Comment by AlexKoff88** [comment]
Here it is:

@article{kozlov2020neural,
  title={Neural network compression framework for fast model inference},
  author={Kozlov, Alexander and Lazarevich, Ivan and Shamporov, Vasily and Lyalyushkin, Nikolay and Gorbachev, Yury},
  journal={arXiv preprint arXiv:2002.08679},
  year={2020}
}

**Comment by yqtianust** [comment]
Thanks.
BTW, Thanks for your tool. Very helpful.
