### ISSUE TITLE
Slower inference with INT8 for NNCF compared to Post-Training Optimization Toolkit and FP32

### ISSUE THREAD

**Issue by summer110669** [openvinotoolkit/nncf_pytorch#123]
Hi, thank you for providing these useful tools. Currently, I'm working on INT8 quantization on both NNCF and POT. I've noticed that the inference time of POT is faster than FP32, which totally makes sense; however, the inference time of NNCF not only is slower than POT but also slower than the original FP32. The benchmark tool results are as follows:

Original FP32:

[Step 1/11] Parsing and validating input arguments
[Step 2/11] Loading Inference Engine
[ INFO ] InferenceEngine:
API version............. 2.1.2020.4.0-359-21e092122f4-releases/2020/4
[ INFO ] Device info
CPU
MKLDNNPlugin............ version 2.1
Build................... 2020.4.0-359-21e092122f4-releases/2020/4

[Step 3/11] Setting device configuration
[Step 4/11] Reading the Intermediate Representation network
[ INFO ] Read network took 57.23 ms
[Step 5/11] Resizing network to match image sizes and given batch
[ INFO ] Network batch size: 1
[Step 6/11] Configuring input of the model
[Step 7/11] Loading the model to the device
[ INFO ] Load network took 294.24 ms
[Step 8/11] Setting optimal runtime parameters
[Step 9/11] Creating infer requests and filling input blobs with images
[ INFO ] Network input 'input0' precision U8, dimensions (NCHW): 1 3 640 640
/opt/intel/openvino_2020.4.287/python/python3.6/openvino/tools/benchmark/utils/inputs_filling.py:71: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
logger.warn("No input files were given: all inputs will be filled with random values!")
[ WARNING ] No input files were given: all inputs will be filled with random values!
[ INFO ] Infer Request 0 filling
[ INFO ] Fill input 'input0' with random values (image is expected)
[Step 10/11] Measuring performance (Start inference asyncronously, 1 inference requests using 1 streams for CPU, limits: 60000 ms duration)
[Step 11/11] Dumping statistics report
Count: 1842 iterations
Duration: 60044.23 ms
Latency: 32.15 ms
Throughput: 30.68 FPS

========================================================================

POT INT8:

[Step 1/11] Parsing and validating input arguments
[Step 2/11] Loading Inference Engine
[ INFO ] InferenceEngine:
API version............. 2.1.2020.4.0-359-21e092122f4-releases/2020/4
[ INFO ] Device info
CPU
MKLDNNPlugin............ version 2.1
Build................... 2020.4.0-359-21e092122f4-releases/2020/4

[Step 3/11] Setting device configuration
[Step 4/11] Reading the Intermediate Representation network
[ INFO ] Read network took 86.67 ms
[Step 5/11] Resizing network to match image sizes and given batch
[ INFO ] Network batch size: 1
[Step 6/11] Configuring input of the model
[Step 7/11] Loading the model to the device
[ INFO ] Load network took 411.73 ms
[Step 8/11] Setting optimal runtime parameters
[Step 9/11] Creating infer requests and filling input blobs with images
[ INFO ] Network input 'input0' precision U8, dimensions (NCHW): 1 3 640 640
/opt/intel/openvino_2020.4.287/python/python3.6/openvino/tools/benchmark/utils/inputs_filling.py:71: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
logger.warn("No input files were given: all inputs will be filled with random values!")
[ WARNING ] No input files were given: all inputs will be filled with random values!
[ INFO ] Infer Request 0 filling
[ INFO ] Fill input 'input0' with random values (image is expected)
[Step 10/11] Measuring performance (Start inference asyncronously, 1 inference requests using 1 streams for CPU, limits: 60000 ms duration)
[Step 11/11] Dumping statistics report
Count: 3245 iterations
Duration: 60032.85 ms
Latency: 18.25 ms
Throughput: 54.05 FPS

===========================================================================

NNCF INT8:

[Step 1/11] Parsing and validating input arguments
[Step 2/11] Loading Inference Engine
[ INFO ] InferenceEngine:
API version............. 2.1.2020.4.0-359-21e092122f4-releases/2020/4
[ INFO ] Device info
CPU
MKLDNNPlugin............ version 2.1
Build................... 2020.4.0-359-21e092122f4-releases/2020/4

[Step 3/11] Setting device configuration
[Step 4/11] Reading the Intermediate Representation network
[ INFO ] Read network took 114.43 ms
[Step 5/11] Resizing network to match image sizes and given batch
[ INFO ] Network batch size: 1
[Step 6/11] Configuring input of the model
[Step 7/11] Loading the model to the device
[ INFO ] Load network took 599.62 ms
[Step 8/11] Setting optimal runtime parameters
[Step 9/11] Creating infer requests and filling input blobs with images
[ INFO ] Network input 'result.1' precision U8, dimensions (NCHW): 1 3 640 640
/opt/intel/openvino_2020.4.287/python/python3.6/openvino/tools/benchmark/utils/inputs_filling.py:71: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
logger.warn("No input files were given: all inputs will be filled with random values!")
[ WARNING ] No input files were given: all inputs will be filled with random values!
[ INFO ] Infer Request 0 filling
[ INFO ] Fill input 'result.1' with random values (image is expected)
[Step 10/11] Measuring performance (Start inference asyncronously, 1 inference requests using 1 streams for CPU, limits: 60000 ms duration)
[Step 11/11] Dumping statistics report
Count: 1291 iterations
Duration: 60082.78 ms
Latency: 46.00 ms
Throughput: 21.49 FPS

===========================================================================

These results are conducted on Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz .

We have found that there is a  difference between the IR model of NNCF and POT, where the FakeQuantize Layer and the activation function happen to be in the opposite order, which leads to more parameters in FakeQuantize Layer in NNCF.   The Neutron visualization results show as follows:

POT INT8:
![pot](https://user-images.githubusercontent.com/41544723/92092698-fff8d980-ee04-11ea-873f-1efa2f3d1216.PNG)

NNCF INT8:
![nncf](https://user-images.githubusercontent.com/41544723/92092722-06875100-ee05-11ea-9c00-7bb0c92e10c9.PNG)

**Comment by vshampor** [comment]
Seems to be related to #117.

Also, it looks like the NNCF path used per-channel activation quantization, while the POT path used per-tensor quantization. This might be a sign of HW config file misalignment between NNCF and POT (our fault), or mismatching configurations between POT and NNCF if you did not use specific HW configuration. Try forcing per-tensor in NNCF via config file parameters (`"per_channel": true`) as a workaround in NNCF and see if it improves the situation.

**Comment by vshampor** [comment]
Try checking out https://github.com/openvinotoolkit/nncf_pytorch/pull/124 to see if it fixes the FakeQuantize order in NNCF.

**Comment by summer110669** [comment]
> Seems to be related to #117.
> 
> Also, it looks like the NNCF path used per-channel activation quantization, while the POT path used per-tensor quantization. This might be a sign of HW config file misalignment between NNCF and POT (our fault), or mismatching configurations between POT and NNCF if you did not use specific HW configuration. Try forcing per-tensor in NNCF via config file parameters (`"per_channel": true`) as a workaround in NNCF and see if it improves the situation.

Hi, thank you for the fast reply :-) 
I used (`"hw_config_type": "cpu"`) on the NNCF config. Did you mean that directly add the (`"per_channel": true`) on the NNCF config? Thank you.

**Comment by vshampor** [comment]
@summer110669 - sorry, made a mistake there - should read `"per_channel": false`, of course. I edited the comment so as not to mislead future readers. Add the `"per_channel": false` line at the same level in the .json structure as the `"algorithm": "quantization"` key-value pair.

**Comment by summer110669** [comment]
> @summer110669 - sorry, made a mistake there - should read `"per_channel": false`, of course. I edited the comment so as not to mislead future readers. Add the `"per_channel": false` line at the same level in the .json structure as the `"algorithm": "quantization"` key-value pair.

I added the "per_channel": false in config as you said, and here's the error:
ERROR:nncf:Invalid NNCF config supplied!
Traceback (most recent call last):
  File "train.py", line 247, in <module>
    main(args)
  File "train.py", line 160, in main
    nncf_config = NNCFConfig.from_json(args.nncf_config)
  File "/usr/local/lib/python3.6/dist-packages/nncf/config.py", line 45, in from_json
    NNCFConfig.validate(loaded_json)
  File "/usr/local/lib/python3.6/dist-packages/nncf/config.py", line 81, in validate
    validate_single_compression_algo_schema(compression_section)
  File "/usr/local/lib/python3.6/dist-packages/nncf/config_schema.py", line 595, in validate_single_compression_algo_schema
    raise type(e)("For algorithm: '{}'\n".format(algo_name) + str(e)).with_traceback(sys.exc_info()[2])
  File "/usr/local/lib/python3.6/dist-packages/nncf/config_schema.py", line 592, in validate_single_compression_algo_schema
    jsonschema.validate(single_compression_algo_dict, schema=REF_VS_ALGO_SCHEMA[algo_name])
  File "/usr/local/lib/python3.6/dist-packages/jsonschema/validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: For algorithm: 'quantization'
Additional properties are not allowed ('per_channel' was unexpected)

Failed validating 'additionalProperties' in schema:
    {'additionalProperties': False,
     'properties': {'activations': {'additionalProperties': False,
                                    'description': 'Constraints to be '
                                                   'applied to model '
                                                   'activations '
                                                   'quantization only. '
                                                   'Overrides higher-level '
                                                   'settings.',
                                    'properties': {'bits': {'description': 'Bitwidth '
                                                                           'to '
                                                                           'quantize '
                                                                           'to.',
                                                            'type': 'number'},
                                                   'ignored_scopes': {'description': 'A '
                                                                                     'list '
                                                                                     'of '
                                                                                     'model '
                                                                                     'control '
                                                                                     'flow '
                                                                                     'graph '
                                                                                     'node '
                                                                                     'scopes '
                                                                                     'to '
                                                                                     'be '
                                                                                     'ignored '
                                                                                     'for '
                                                                                     'this '
                                                                                     'operation '
                                                                                     '- '
                                                                                     'functions '
                                                                                     'as '
                                                                                     'a '
                                                                                     "'blacklist'. "
                                                                                     'Optional.',
                                                                      'oneOf': [{'items': {'type': 'string'},
                                                                                 'type': 'array'},
                                                                                {'type': 'string'}]},
                                                   'mode': {'description': 'Mode '
                                                                           'of '
                                                                           'quantization',
                                                            'type': 'string'},
                                                   'per_channel': {'description': 'Whether '
                                                                                  'to '
                                                                                  'quantize '
                                                                                  'inputs '
                                                                                  'per '
                                                                                  'channel '
                                                                                  '(i.e. '
                                                                                  'per '
                                                                                  '0-th '
                                                                                  'dimension '
                                                                                  'for '
                                                                                  'weight '
                                                                                  'quantization, '
                                                                                  'and '
                                                                                  'per '
                                                                                  '1-st '
                                                                                  'dimension '
                                                                                  'for '
                                                                                  'activation '
                                                                                  'quantization)',
                                                                   'type': 'boolean'},
                                                   'signed': {'description': 'Whether '
                                                                             'to '
                                                                             'use '
                                                                             'signed '
                                                                             'or '
                                                                             'unsigned '
                                                                             'input/output '
                                                                             'values '
                                                                             'for '
                                                                             'quantization. '
                                                                             'If '
                                                                             'specified '
                                                                             'as '
                                                                             'unsigned '
                                                                             'and '
                                                                             'the '
                                                                             'input '
                                                                             'values '
                                                                             'during '
                                                                             'initialization '
                                                                             'have '
                                                                             'differing '
                                                                             'signs, '
                                                                             'will '
                                                                             'reset '
                                                                             'to '
                                                                             'performing '
                                                                             'signed '
                                                                             'quantization '
                                                                             'instead.',
                                                              'type': 'boolean'},
                                                   'target_scopes': {'description': 'A '
                                                                                    'list '
                                                                                    'of '
                                                                                    'model '
                                                                                    'control '
                                                                                    'flow '
                                                                                    'graph '
                                                                                    'node '
                                                                                    'scopes '
                                                                                    'to '
                                                                                    'be '
                                                                                    'considered '
                                                                                    'for '
                                                                                    'this '
                                                                                    'operation '
                                                                                    '- '
                                                                                    'functions '
                                                                                    'as '
                                                                                    'a '
                                                                                    "'whitelist'. "
                                                                                    'Optional.',
                                                                     'oneOf': [{'items': {'type': 'string'},
                                                                                'type': 'array'},
                                                                               {'type': 'string'}]}},
                                    'type': 'object'},
                    'algorithm': {'const': 'quantization'},
                    'export_to_onnx_standard_ops': {'description': 'Determines '
                                                                   'how '
                                                                   'should '
                                                                   'the '
                                                                   'additional '
                                                                   'quantization '
                                                                   'operations '
                                                                   'be '
                                                                   'exported '
                                                                   'into '
                                                                   'the '
                                                                   'ONNX '
                                                                   'format. '
                                                                   'Set '
                                                                   'this '
                                                                   'to '
                                                                   'false '
                                                                   'for '
                                                                   'export '
                                                                   'to '
                                                                   'OpenVINO-supported '
                                                                   'FakeQuantize '
                                                                   'ONNX, '
                                                                   'or to '
                                                                   'true '
                                                                   'for '
                                                                   'export '
                                                                   'to '
                                                                   'ONNX '
                                                                   'standard '
                                                                   'QuantizeLinear-DequantizeLinear '
                                                                   'node '
                                                                   'pairs '
                                                                   '(8-bit '
                                                                   'quantization '
                                                                   'only '
                                                                   'in the '
                                                                   'latter '
                                                                   'case). '
                                                                   'Default: '
                                                                   'false',
                                                    'type': 'boolean'},
                    'ignored_scopes': {'description': 'A list of model '
                                                      'control flow graph '
                                                      'node scopes to be '
                                                      'ignored for this '
                                                      'operation - '
                                                      'functions as a '
                                                      "'blacklist'. "
                                                      'Optional.',
                                       'items': {'type': 'string'},
                                       'type': ['array', 'string']},
                    'initializer': {'additionalProperties': False,
                                    'properties': {'batchnorm_adaptation': {'additionalProperties': False,
                                                                            'properties': {'num_bn_adaptation_steps': {'description': 'Number '
                                                                                                                                      'of '
                                                                                                                                      'batches '
                                                                                                                                      'from '
                                                                                                                                      'the '
                                                                                                                                      'training '
                                                                                                                                      'dataset '
                                                                                                                                      'to '
                                                                                                                                      'use '
                                                                                                                                      'for '
                                                                                                                                      'model '
                                                                                                                                      'inference '
                                                                                                                                      'during '
                                                                                                                                      'the '
                                                                                                                                      'BatchNorm '
                                                                                                                                      'statistics '
                                                                                                                                      'adaptation '
                                                                                                                                      'procedure '
                                                                                                                                      'for '
                                                                                                                                      'the '
                                                                                                                                      'compressed '
                                                                                                                                      'model',
                                                                                                                       'type': 'number'},
                                                                                           'num_bn_forget_steps': {'description': 'Number '
                                                                                                                                  'of '
                                                                                                                                  'batches '
                                                                                                                                  'from '
                                                                                                                                  'the '
                                                                                                                                  'training '
                                                                                                                                  'dataset '
                                                                                                                                  'to '
                                                                                                                                  'use '
                                                                                                                                  'for '
                                                                                                                                  'model '
                                                                                                                                  'inference '
                                                                                                                                  'during '
                                                                                                                                  'the '
                                                                                                                                  'BatchNorm '
                                                                                                                                  'statistics '
                                                                                                                                  'adaptation '
                                                                                                                                  'in '
                                                                                                                                  'the '
                                                                                                                                  'initial '
                                                                                                                                  'statistics '
                                                                                                                                  'forgetting '
                                                                                                                                  'step',
                                                                                                                   'type': 'number'}},
                                                                            'type': 'object'},
                                                   'precision': {'additionalProperties': False,
                                                                 'properties': {'bits': {'description': 'A '
                                                                                                        'list '
                                                                                                        'of '
                                                                                                        'bitwidth '
                                                                                                        'to '
                                                                                                        'choose '
                                                                                                        'from '
                                                                                                        'when '
                                                                                                        'performing '
                                                                                                        'precision '
                                                                                                        'initialization.',
                                                                                         'examples': [[4,
                                                                                                       8]],
                                                                                         'items': {'type': 'number'},
                                                                                         'type': 'array'},
                                                                                'bitwidth_per_scope': {'description': 'Manual '
                                                                                                                      'settings '
                                                                                                                      'for '
                                                                                                                      'the '
                                                                                                                      'quantizer '
                                                                                                                      'bitwidths. '
                                                                                                                      'Scopes '
                                                                                                                      'are '
                                                                                                                      'used '
                                                                                                                      'to '
                                                                                                                      'identify '
                                                                                                                      'the '
                                                                                                                      'quantizers.',
                                                                                                       'items': {'description': 'A '
                                                                                                                                'tuple '
                                                                                                                                'of '
                                                                                                                                'a '
                                                                                                                                'bitwidth '
                                                                                                                                'and '
                                                                                                                                'a '
                                                                                                                                'scope '
                                                                                                                                'of '
                                                                                                                                'the '
                                                                                                                                'quantizer '
                                                                                                                                'to '
                                                                                                                                'assign '
                                                                                                                                'the '
                                                                                                                                'bitwidth '
                                                                                                                                'to.',
                                                                                                                 'items': [{'type': 'number'},
                                                                                                                           {'type': 'string'}],
                                                                                                                 'type': 'array'},
                                                                                                       'type': 'array'},
                                                                                'iter_number': {'description': 'Maximum '
                                                                                                               'number '
                                                                                                               'of '
                                                                                                               'iterations '
                                                                                                               'of '
                                                                                                               'Hutchinson '
                                                                                                               'algorithm '
                                                                                                               'to '
                                                                                                               'Estimate '
                                                                                                               'Hessian '
                                                                                                               'trace, '
                                                                                                               '200 '
                                                                                                               'by '
                                                                                                               'default',
                                                                                                'type': 'number'},
                                                                                'num_data_points': {'description': 'Number '
                                                                                                                   'of '
                                                                                                                   'data '
                                                                                                                   'points '
                                                                                                                   'to '
                                                                                                                   'iteratively '
                                                                                                                   'estimate '
                                                                                                                   'Hessian '
                                                                                                                   'trace, '
                                                                                                                   '200 '
                                                                                                                   'by '
                                                                                                                   'default.',
                                                                                                    'type': 'number'},
                                                                                'tolerance': {'description': 'Minimum '
                                                                                                             'relative '
                                                                                                             'tolerance '
                                                                                                             'for '
                                                                                                             'stopping '
                                                                                                             'the '
                                                                                                             'Hutchinson '
                                                                                                             'algorithm. '
                                                                                                             "It's "
                                                                                                             'calculated  '
                                                                                                             'between '
                                                                                                             'mean '
                                                                                                             'average '
                                                                                                             'trace '
                                                                                                             'from '
                                                                                                             'previous '
                                                                                                             'iteration '
                                                                                                             'and '
                                                                                                             'current '
                                                                                                             'one. '
                                                                                                             '1e-5 '
                                                                                                             'by '
                                                                                                             'defaultbitwidth_per_scope',
                                                                                              'type': 'number'},
                                                                                'type': {'description': 'Type '
                                                                                                        'of '
                                                                                                        'precision '
                                                                                                        'initialization.',
                                                                                         'type': 'string'}},
                                                                 'type': 'object'},
                                                   'range': {'additionalProperties': False,
                                                             'properties': {'max_percentile': {'description': 'For '
                                                                                                              "'percentile' "
                                                                                                              'type '
                                                                                                              '- '
                                                                                                              'specify '
                                                                                                              'the '
                                                                                                              'percentile '
                                                                                                              'of '
                                                                                                              'input '
                                                                                                              'value '
                                                                                                              'histograms '
                                                                                                              'to '
                                                                                                              'be '
                                                                                                              'set '
                                                                                                              'as '
                                                                                                              'the '
                                                                                                              'initial '
                                                                                                              'value '
                                                                                                              'for '
                                                                                                              'maximum '
                                                                                                              'quantizer '
                                                                                                              'input',
                                                                                               'type': 'number'},
                                                                            'min_percentile': {'description': 'For '
                                                                                                              "'percentile' "
                                                                                                              'type '
                                                                                                              '- '
                                                                                                              'specify '
                                                                                                              'the '
                                                                                                              'percentile '
                                                                                                              'of '
                                                                                                              'input '
                                                                                                              'value '
                                                                                                              'histograms '
                                                                                                              'to '
                                                                                                              'be '
                                                                                                              'set '
                                                                                                              'as '
                                                                                                              'the '
                                                                                                              'initial '
                                                                                                              'value '
                                                                                                              'for '
                                                                                                              'minimum '
                                                                                                              'quantizer '
                                                                                                              'input',
                                                                                               'type': 'number'},
                                                                            'num_init_steps': {'description': 'Number '
                                                                                                              'of '
                                                                                                              'batches '
                                                                                                              'from '
                                                                                                              'the '
                                                                                                              'training '
                                                                                                              'dataset '
                                                                                                              'to '
                                                                                                              'consume '
                                                                                                              'as '
                                                                                                              'sample '
                                                                                                              'model '
                                                                                                              'inputs '
                                                                                                              'for '
                                                                                                              'purposes '
                                                                                                              'of '
                                                                                                              'setting '
                                                                                                              'initial '
                                                                                                              'minimum '
                                                                                                              'and '
                                                                                                              'maximum '
                                                                                                              'quantization '
                                                                                                              'ranges',
                                                                                               'type': 'number'},
                                                                            'type': {'description': 'Type '
                                                                                                    'of '
                                                                                                    'the '
                                                                                                    'initializer '
                                                                                                    '- '
                                                                                                    'determines '
                                                                                                    'which '
                                                                                                    'statistics '
                                                                                                    'gathered '
                                                                                                    'during '
                                                                                                    'initialization '
                                                                                                    'will '
                                                                                                    'be '
                                                                                                    'used '
                                                                                                    'to '
                                                                                                    'initialize '
                                                                                                    'the '
                                                                                                    'quantization '
                                                                                                    'ranges',
                                                                                     'type': 'string'}},
                                                             'type': 'object'}},
                                    'type': 'object'},
                    'params': {'additionalProperties': False,
                               'properties': {'activations_quant_start_epoch': {'description': 'Epoch '
                                                                                               'to '
                                                                                               'start '
                                                                                               'binarizing '
                                                                                               'activations',
                                                                                'type': 'number'},
                                              'base_lr': {'description': 'Initial '
                                                                         'value '
                                                                         'of '
                                                                         'learning '
                                                                         'rate',
                                                          'type': 'number'},
                                              'base_wd': {'description': 'Initial '
                                                                         'value '
                                                                         'of '
                                                                         'weight '
                                                                         'decay',
                                                          'type': 'number'},
                                              'batch_multiplier': {'description': 'Gradients '
                                                                                  'will '
                                                                                  'be '
                                                                                  'accumulated '
                                                                                  'for '
                                                                                  'this '
                                                                                  'number '
                                                                                  'of '
                                                                                  'batches '
                                                                                  'before '
                                                                                  'doing '
                                                                                  'a '
                                                                                  "'backward' "
                                                                                  'call. '
                                                                                  'Increasing '
                                                                                  'this '
                                                                                  'may '
                                                                                  'improve '
                                                                                  'training '
                                                                                  'quality, '
                                                                                  'since '
                                                                                  'binarized '
                                                                                  'networks '
                                                                                  'exhibit '
                                                                                  'noisy '
                                                                                  'gradients '
                                                                                  'requiring '
                                                                                  'larger '
                                                                                  'batch '
                                                                                  'sizes '
                                                                                  'than '
                                                                                  'could '
                                                                                  'be '
                                                                                  'accomodated '
                                                                                  'by '
                                                                                  'GPUs',
                                                                   'type': 'number'},
                                              'disable_wd_start_epoch': {'description': 'Epoch '
                                                                                        'to '
                                                                                        'disable '
                                                                                        'weight '
                                                                                        'decay '
                                                                                        'in '
                                                                                        'the '
                                                                                        'optimizer',
                                                                         'type': 'number'},
                                              'lr_poly_drop_duration_epochs': {'description': 'Duration, '
                                                                                              'in '
                                                                                              'epochs, '
                                                                                              'of '
                                                                                              'the '
                                                                                              'learning '
                                                                                              'rate '
                                                                                              'dropping '
                                                                                              'process.',
                                                                               'type': 'number'},
                                              'lr_poly_drop_start_epoch': {'description': 'Epoch '
                                                                                          'to '
                                                                                          'start '
                                                                                          'dropping '
                                                                                          'the '
                                                                                          'learning '
                                                                                          'rate',
                                                                           'type': 'number'},
                                              'weights_quant_start_epoch': {'description': 'Epoch '
                                                                                           'to '
                                                                                           'start '
                                                                                           'binarizing '
                                                                                           'weights',
                                                                            'type': 'number'}},
                               'type': 'object'},
                    'quantizable_subgraph_patterns': {'description': 'Each '
                                                                     'sub-list '
                                                                     'in '
                                                                     'this '
                                                                     'list '
                                                                     'will '
                                                                     'correspond '
                                                                     'to a '
                                                                     'sequence '
                                                                     'of '
                                                                     'operations '
                                                                     'in '
                                                                     'the '
                                                                     'model '
                                                                     'control '
                                                                     'flow '
                                                                     'graph '
                                                                     'that '
                                                                     'will '
                                                                     'have '
                                                                     'a '
                                                                     'quantizer '
                                                                     'appended '
                                                                     'at '
                                                                     'the '
                                                                     'end '
                                                                     'of '
                                                                     'the '
                                                                     'sequence',
                                                      'examples': [['cat',
                                                                    'batch_norm'],
                                                                   'h_swish'],
                                                      'items': {'items': {'type': 'string'},
                                                                'type': ['array',
                                                                         'string']},
                                                      'type': 'array'},
                    'quantize_inputs': {'default': True,
                                        'description': 'Whether the model '
                                                       'inputs should be '
                                                       'immediately '
                                                       'quantized prior to '
                                                       'any other model '
                                                       'operations.',
                                        'type': 'boolean'},
                    'quantize_outputs': {'default': False,
                                         'description': 'Whether the model '
                                                        'outputs should be '
                                                        'additionally '
                                                        'quantized.',
                                         'type': 'boolean'},
                    'scope_overrides': {'description': 'This option is '
                                                       'used to specify '
                                                       'overriding '
                                                       'quantization '
                                                       'constraints for '
                                                       'specific '
                                                       'scope,e.g. in case '
                                                       'you need to '
                                                       'quantize a single '
                                                       'operation '
                                                       'differently than '
                                                       'the rest of the '
                                                       'model.',
                                        'patternProperties': {'.*': {'additionalProperties': False,
                                                                     'properties': {'bits': {'description': 'Bitwidth '
                                                                                                            'to '
                                                                                                            'quantize '
                                                                                                            'to.',
                                                                                             'type': 'number'},
                                                                                    'mode': {'description': 'Mode '
                                                                                                            'of '
                                                                                                            'quantization',
                                                                                             'type': 'string'},
                                                                                    'per_channel': {'description': 'Whether '
                                                                                                                   'to '
                                                                                                                   'quantize '
                                                                                                                   'inputs '
                                                                                                                   'per '
                                                                                                                   'channel '
                                                                                                                   '(i.e. '
                                                                                                                   'per '
                                                                                                                   '0-th '
                                                                                                                   'dimension '
                                                                                                                   'for '
                                                                                                                   'weight '
                                                                                                                   'quantization, '
                                                                                                                   'and '
                                                                                                                   'per '
                                                                                                                   '1-st '
                                                                                                                   'dimension '
                                                                                                                   'for '
                                                                                                                   'activation '
                                                                                                                   'quantization)',
                                                                                                    'type': 'boolean'},
                                                                                    'signed': {'description': 'Whether '
                                                                                                              'to '
                                                                                                              'use '
                                                                                                              'signed '
                                                                                                              'or '
                                                                                                              'unsigned '
                                                                                                              'input/output '
                                                                                                              'values '
                                                                                                              'for '
                                                                                                              'quantization. '
                                                                                                              'If '
                                                                                                              'specified '
                                                                                                              'as '
                                                                                                              'unsigned '
                                                                                                              'and '
                                                                                                              'the '
                                                                                                              'input '
                                                                                                              'values '
                                                                                                              'during '
                                                                                                              'initialization '
                                                                                                              'have '
                                                                                                              'differing '
                                                                                                              'signs, '
                                                                                                              'will '
                                                                                                              'reset '
                                                                                                              'to '
                                                                                                              'performing '
                                                                                                              'signed '
                                                                                                              'quantization '
                                                                                                              'instead.',
                                                                                               'type': 'boolean'}},
                                                                     'type': 'object'}},
                                        'type': 'object'},
                    'target_scopes': {'description': 'A list of model '
                                                     'control flow graph '
                                                     'node scopes to be '
                                                     'considered for this '
                                                     'operation - '
                                                     'functions as a '
                                                     "'whitelist'. "
                                                     'Optional.',
                                      'items': {'type': 'string'},
                                      'type': ['array', 'string']},
                    'weights': {'additionalProperties': False,
                                'description': 'Constraints to be applied '
                                               'to model weights '
                                               'quantization only. '
                                               'Overrides higher-level '
                                               'settings.',
                                'properties': {'bits': {'description': 'Bitwidth '
                                                                       'to '
                                                                       'quantize '
                                                                       'to.',
                                                        'type': 'number'},
                                               'ignored_scopes': {'description': 'A '
                                                                                 'list '
                                                                                 'of '
                                                                                 'model '
                                                                                 'control '
                                                                                 'flow '
                                                                                 'graph '
                                                                                 'node '
                                                                                 'scopes '
                                                                                 'to '
                                                                                 'be '
                                                                                 'ignored '
                                                                                 'for '
                                                                                 'this '
                                                                                 'operation '
                                                                                 '- '
                                                                                 'functions '
                                                                                 'as '
                                                                                 'a '
                                                                                 "'blacklist'. "
                                                                                 'Optional.',
                                                                  'oneOf': [{'items': {'type': 'string'},
                                                                             'type': 'array'},
                                                                            {'type': 'string'}]},
                                               'mode': {'description': 'Mode '
                                                                       'of '
                                                                       'quantization',
                                                        'type': 'string'},
                                               'per_channel': {'description': 'Whether '
                                                                              'to '
                                                                              'quantize '
                                                                              'inputs '
                                                                              'per '
                                                                              'channel '
                                                                              '(i.e. '
                                                                              'per '
                                                                              '0-th '
                                                                              'dimension '
                                                                              'for '
                                                                              'weight '
                                                                              'quantization, '
                                                                              'and '
                                                                              'per '
                                                                              '1-st '
                                                                              'dimension '
                                                                              'for '
                                                                              'activation '
                                                                              'quantization)',
                                                               'type': 'boolean'},
                                               'signed': {'description': 'Whether '
                                                                         'to '
                                                                         'use '
                                                                         'signed '
                                                                         'or '
                                                                         'unsigned '
                                                                         'input/output '
                                                                         'values '
                                                                         'for '
                                                                         'quantization. '
                                                                         'If '
                                                                         'specified '
                                                                         'as '
                                                                         'unsigned '
                                                                         'and '
                                                                         'the '
                                                                         'input '
                                                                         'values '
                                                                         'during '
                                                                         'initialization '
                                                                         'have '
                                                                         'differing '
                                                                         'signs, '
                                                                         'will '
                                                                         'reset '
                                                                         'to '
                                                                         'performing '
                                                                         'signed '
                                                                         'quantization '
                                                                         'instead.',
                                                          'type': 'boolean'},
                                               'target_scopes': {'description': 'A '
                                                                                'list '
                                                                                'of '
                                                                                'model '
                                                                                'control '
                                                                                'flow '
                                                                                'graph '
                                                                                'node '
                                                                                'scopes '
                                                                                'to '
                                                                                'be '
                                                                                'considered '
                                                                                'for '
                                                                                'this '
                                                                                'operation '
                                                                                '- '
                                                                                'functions '
                                                                                'as '
                                                                                'a '
                                                                                "'whitelist'. "
                                                                            'type': 'array'},
                                                                           {'type': 'string'}]}},
                                'type': 'object'}},
     'required': ['algorithm'],
     'type': 'object'}

On instance:
    {'algorithm': 'quantization',
     'initializer': {'range': {'num_init_steps': 50}},
     'per_channel': False}

-----------------------------------------------------------------------
I also tried  'per_channel': False in the config, but it is still incorrect. The error shows as follows:
Traceback (most recent call last):
  File "train.py", line 247, in <module>
    main(args)
  File "train.py", line 160, in main
    nncf_config = NNCFConfig.from_json(args.nncf_config)
  File "/usr/local/lib/python3.6/dist-packages/nncf/config.py", line 44, in from_json
    loaded_json = json.load(f)
  File "/usr/local/lib/python3.6/dist-packages/jstyleson.py", line 127, in load
    return loads(fp.read(), **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jstyleson.py", line 123, in loads
    return json.loads(dispose(text), **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 10 column 18 (char 215)

**Comment by vshampor** [comment]
Try `"activations": { "per_channel": false }` at the same JSON level then

**Comment by vshampor** [comment]
@summer110669 have you had any luck with this yet?

**Comment by rosspleban** [comment]
@summer110669 Have you been able to improve nncf inference time?
