### ISSUE TITLE
Is there any way to support two inputs?

### ISSUE THREAD

**Issue by wtaodd** [openvinotoolkit/nncf_pytorch#145]
Is there any way to support two inputs?

**Comment by aleksei-kashapov** [comment]
NNCF support any input that demands your model.
You just need to make dummy_forward function that would make dummy arguments for model's forward pass. Then to give that function to  create_compressed_model() to get wrapped model

See the example below:

```
    nncf_config = NNCFConfig(cfg)

    def dummy_forward(model):
        input_size = nncf_config.get("input_info").get('sample_size')
        device = next(model.parameters()).device
        input_args = ([torch.randn(input_size).to(device), ],)
        input_kwargs = dict(return_loss=False, dummy_forward=True)
        model(*input_args, **input_kwargs)

    model.dummy_forward_fn = dummy_forward

    compression_ctrl, model = create_compressed_model(model, nncf_config, dummy_forward_fn=dummy_forward)
```

If it doesn't work for you please let me know

**Comment by vshampor** [comment]
@wtaodd you can use the way @aleksei-kashapov suggested, but you can also specify multiple inputs in the NNCF .json config file as well, for instance:
```
"input_info": [
    {
        "sample_size": [2, 3, 224, 224],
    },
    {
        "sample_size": [2, 1, 32, 32],
    }
]

**Comment by wtaodd** [comment]
it works，thk!
