### ISSUE TITLE
Performance gap in mmdetection 

### ISSUE THREAD

**Issue by Wang-zipeng** [openvinotoolkit/nncf_pytorch#148]
I'm sorry. I am back.
I have been tried  retinanet_r50_fpn_1x_int8.py in mmdetection, there is nothing wrong in training and evaluation.
But i only got this result in coco2017 val, docs showed that retinanet can reached 34.7 or 35.3 average box mAP on the coco_2017_val dataset.
My result are as follows:
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.260
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.420
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.272
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.143
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.292
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.336
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.258
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.425
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.453
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.260
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.494
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.600

I didn't change anything in config file expect changing samples_per_gpu from 6 to 4 because my gpu can't allocate enough memory. My cuda version is 10.2, pytorch is 1.6.0.
If you need any other information please contact me

**Comment by Wang-zipeng** [comment]
Maybe i know what's wrong, your base model is 'retinanet_r50_fpn_1x_voc0712_20200617-47cbdd0e.pth', but your dataset is coco, i think this is why performance descend hardly. Is there something wrong in my understanding or operation?

**Comment by Wang-zipeng** [comment]
I have been compare performance between compressed model and official mscoco trained model.
the model name is 'retinanet_r50_fpn_1x_coco_20200130-c2398f9e.pth'.  
nncf run evaluation on single 1080Ti as 13.8 task/s and official implementation with model 13.6 task/s, almost the same speed.
and nncf model consume about 2121MB GPU memory at maximum, official mmdetection 1515 GPU memory at maximum, after quantization, model seem to consume more GPU memory. Is this right?
To util the nncf to speedup or reduce memory usage, should i convert the model to onnx and use the openvino?

**Comment by vshampor** [comment]
@Wang-zipeng 
> To util the nncf to speedup or reduce memory usage, should i convert the model to onnx and use the openvino?

Correct.

**Comment by aleksei-kashapov** [comment]
> Maybe i know what's wrong, your base model is 'retinanet_r50_fpn_1x_voc0712_20200617-47cbdd0e.pth', but your dataset is coco, i think this is why performance descend hardly. Is there something wrong in my understanding or operation?

@Wang-zipeng , you are right. This model was pre-trained on VOC dataset. 
If you want pretrained retinanet_r50_fpn_1x on COCO you can change the line 
`load_from = "https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmdetection/v2.0/pascal_voc/retinanet_r50_fpn_1x_voc0712/retinanet_r50_fpn_1x_voc0712_20200617-47cbdd0e.pth"`
to 
`load_from="http://download.openmmlab.com/mmdetection/v2.0/retinanet/retinanet_r50_fpn_2x_coco/retinanet_r50_fpn_2x_coco_20200131-fdb43119.pth"`

Also, there are different pretrained retinanet models which you can use: https://github.com/open-mmlab/mmdetection/tree/master/configs/retinanet
