### ISSUE TITLE
MMDetection fine tuning error

### ISSUE THREAD

**Issue by ksmultiacc3** [openvinotoolkit/nncf_pytorch#152]
I am getting the following error on running the demo retinanet_r50_fpn_1x_int8.py example. Any suggestions of what could be causing it?
`args_kwargs_tuple = data_loader.get_inputs(loaded_item)
  File "/home/.conda/envs/nncf2/lib/python3.6/site-packages/nncf-1.4.1-py3.6.egg/nncf/initialization.py", line 56, in get_inputs
    raise NotImplementedError
NotImplementedError`

I had followed the master branch of nncf and mmdet commit id: c77ccbbf235c0eb50a4440698eefc2ae199f837f

**Comment by aleksei-kashapov** [comment]
Dear @ksmultiacc3,

I am a little bit confused. Are you using our patch for mmdetection?

**Comment by ksmultiacc3** [comment]
I was able to run the quantization aware fine tuning using this [https://github.com/aleksei-kashapov/nncf_pytorch/tree/update_mmdet_patch](https://github.com/aleksei-kashapov/nncf_pytorch/tree/update_mmdet_patch)
branch
