### ISSUE TITLE
How to get int8 IR model (via int8 onnx model)? OpenVINO mo.py --data-type options only supports fp16,fp32

### ISSUE THREAD

**Issue by nsk-lab** [openvinotoolkit/nncf_pytorch#157]
I want to finetune a detection model with int8-awareness and convert it to INT8 IR model to achieve acceleration.
The problem is that I cannot find the way to export INT8 IR model.

I found below statement [here](https://github.com/openvinotoolkit/nncf_pytorch/blob/develop/examples/object_detection/README.md#export-to-openvino-intermediate-representation-ir
), but the `tutorial` link is just a link to OpenVINO top page.
> To export a model to OpenVINO IR and run it using Intel Deep Learning Deployment Toolkit please refer to this tutorial.

I also searched precision-related pages [like this](https://docs.openvinotoolkit.org/latest/pot_docs_LowPrecisionOptimizationGuide.html) in OpenVINO Developer Guides,
but could not find any helpful info.

I know ModelOptmizer tool `mo.py` can convert onnx to IR model,
but --data-type options only supports fp16 and fp32.

**Comment by vshampor** [comment]
Greetings, @nsk-lab !

The INT8 ONNX model differs from an FP32 ONNX model by the additional nodes specifying quantization in-model. No additional Model Optimizer parameters are required to handle such models - the INT8 IR will be produced automatically if you supply an INT8 ONNX as input.

**Comment by nsk-lab** [comment]
@vshampor Thank you for your reply.

I could train my model with int8 optimization and export to ONNX file (which include FakeQantize nodes).
Also I could convert it to IR mode.

But when I load the IR model by `openvino.inference_engine.ie_api.IECore.load_network`, following error occurs
```
  File "ie_api.pyx", line 178, in openvino.inference_engine.ie_api.IECore.load_network
  File "ie_api.pyx", line 187, in openvino.inference_engine.ie_api.IECore.load_network
RuntimeError: Incorrect number of input edges for layer 560/variance/Fused_Add_
```
I attach visualization by [netron](https://github.com/lutzroeder/netron). 
It seems that the top left Add node is ok but bottom left Add node `560/variance/Fused_Add_` has wrong number of input even though the netron visualizer shows 2 input node as I expected.
![image](https://user-images.githubusercontent.com/58692908/94664805-4ed35980-0346-11eb-8ff9-b140ece20298.png)

Could you give me advice?
Is `560/variance/Fused_Add_`  interpreted as having only 1 input? or some other problem?
any suggestions are welcome

**Comment by vshampor** [comment]
@nsk-lab does the problem persist in the FP32 IR, or does it only appear for the INT8 IR?

**Comment by nsk-lab** [comment]
When I do not use NNCF, I could load the model.
I did not try IR model trained by NNCF with FP32 (and converted to IR)

**Comment by nsk-lab** [comment]
@vshampor (I forget mention)

**Comment by vshampor** [comment]
@nsk-lab strange as it is, I'm inclined to believe that this is a bug in OpenVINO's Model Optimizer. Please raise an issue within the https://github.com/openvinotoolkit/openvino repository which owns Model Optimizer. In the meanwhile you can try using the `"export_to_onnx_standard_ops": true` option to produce an ONNX INT8 model which uses ONNX's standard QuantizeLinear/DequantizeLinear operators so that it can be loadable using `onnxruntime`. Successfully running INT8 inference through `onnxruntime` can give you additional confidence that NNCF's output ONNX files are OK.
