### ISSUE TITLE
compression_loss

### ISSUE THREAD

**Issue by sroot0** [openvinotoolkit/nncf_pytorch#196]
compression_loss always equal  zero in my trainling process, does it have same problems?

**Comment by vanyalzr** [comment]
Hi @sroot0,

Please refer to the answer [here](https://github.com/openvinotoolkit/nncf_pytorch/issues/44). In general, the compression loss is supposed to be zero; it is non-zero for some specific regularization-based algos (e.g. RB sparsity in NNCF).

**Comment by sroot0** [comment]
thank you
