### ISSUE TITLE
int8 seem to speedup little in Mask-RCNN

### ISSUE THREAD

**Issue by Wang-zipeng** [openvinotoolkit/nncf_pytorch#202]
Normally Mask-RCNN infer time is about 870ms on i5-8500 with openvino on our machine, and Mask-RCNN infer time is about 740ms on the same machine, is this right?
my nncf_config is 
    compression=[
        dict(
            algorithm='quantization',
            initializer=dict(range=dict(num_init_steps=5)))
    ]

**Comment by vshampor** [comment]
@Wang-zipeng if this is an OpenVINO issue, please submit it to the corresponding repository:
github.com/openvinotoolkit/openvino
