### ISSUE TITLE
export to onnx error

### ISSUE THREAD

**Issue by sroot0** [openvinotoolkit/nncf_pytorch#203]
When I perform int 4 quantization, an error is reported when exporting onnx
report is 
  File "/root/miniconda3/envs/nncf/lib/python3.7/site-packages/nncf/quantization/layers.py", line 404, in run_export_quantization
    input_high_tuned)
  File "/root/miniconda3/envs/nncf/lib/python3.7/site-packages/nncf/quantization/quantize_functions.py", line 151, in get_scale_zp_from_input_low_input_high
    assert levels in [255, 256], "Can only export to INT8 256-level ONNX Quantize/Dequantize pairs"
AssertionError: Can only export to INT8 256-level ONNX Quantize/Dequantize pairs

**Comment by AlexKoff88** [comment]
@sroot0, it seems you are going to export your model to standard ONNX format with QuantizeLinear/Dequantize linear operations. But they do not support non-INT8 data types. If you are planning to use OpenVINO there is another way to export.

**Comment by sroot0** [comment]
> @ sroot0，似乎您将使用QuantizeLinear / Dequantize线性运算将模型导出为标准ONNX格式。但是它们不支持非INT8数据类型。如果您打算使用OpenVINO，则有另一种导出方法。

call you tell me  the other way to export model ?

**Comment by AlexKoff88** [comment]
You should set "export_to_onnx_standard_ops": False, as a parameter of quantization algorithm

**Comment by sroot0** [comment]
> You should set "export_to_onnx_standard_ops": False, as a parameter of quantization algorithm

  i will try it ,thank  you very  much

**Comment by sroot0** [comment]
> 您应将“ export_to_onnx_standard_ops”设置为：False，作为量化算法的参数

I have set false, but I still get an error when exporting to an onnx file
![image](https://user-images.githubusercontent.com/50287916/96836531-b11c0780-1477-11eb-8394-44c5195aa5f8.png)
![QQ截图20201022114532](https://user-images.githubusercontent.com/50287916/96836570-bf6a2380-1477-11eb-9d51-a99e79f2597f.png)

**Comment by AlexKoff88** [comment]
@sroot0, what kind of model are you trying to quantize?

@vshampor, do we have this check even when we "export_to_onnx_standard_ops" false?

**Comment by sroot0** [comment]
> 您应将“ export_to_onnx_standard_ops”设置为：False，作为量化算法的参数
![image](https://user-images.githubusercontent.com/50287916/96836363-73b77a00-1477-11eb-94ef-8db2996d87cb.png)



> @sroot0, what kind of model are you trying to quantize?
> 
> @vshampor, do we have this check even when we "export_to_onnx_standard_ops" false?

model is alexnet, vgg16 ,and res18 , this example is alexnet, dataset  is Cifar10

**Comment by vshampor** [comment]
@sroot0 make sure you are using the latest NNCF version from the `develop` branch.

**Comment by sroot0** [comment]
> @sroot0 make sure you are using the latest NNCF version from the `develop` branch.

The nncf software I am using was installed by pip in October this year. Is this the latest version? Do I need to uninstall and reinstall it?

**Comment by vshampor** [comment]
@sroot0 
https://github.com/openvinotoolkit/nncf_pytorch#as-a-package-built-from-a-checked-out-repository

**Comment by sroot0** [comment]
> @ sroot0
> https://github.com/openvinotoolkit/nncf_pytorch#as-a-package-built-from-a-checked-out-repository

thank you for your help
