### ISSUE TITLE
openvivo inference

### ISSUE THREAD

**Issue by sroot0** [openvinotoolkit/nncf_pytorch#205]
when i want inference model in openvivo ,   When converting an onnx file, OpenVivo shows that it only supports a data_type in the form of Float32 or Float16, so how can I do model inference in INT8 or lower Numbers?
this is error report
C:\Program Files (x86)\Intel\openvino_2021.1.110\deployment_tools\model_optimizer>python  mo.py --input_model=E:\NNCF\Alexnet\int8\ONNX\model.onnx --output_dir=E:\NNCF\Alexnet\int8\ONNX\output --model_name=model_int8  --data_type=int8
usage: mo.py [options]
mo.py: error: argument --data_type: invalid choice: 'int8' (choose from 'FP16', 'FP32', 'half', 'float')

**Comment by AlexKoff88** [comment]
@sroot0, please use the FP16 option. In the common case, the model parameters will be stored in FP16 but they will be converted to INT8 for the layers which contain quantization parameters. BTW, what OpenVINO version do you use?

**Comment by sroot0** [comment]
> @ sroot0，请使用FP16选项。在通常情况下，模型参数将存储在FP16中，但对于包含量化参数的图层，它们将被转换为INT8。顺便说一句，您使用什么OpenVINO版本？

The latest version， Thanks for your answer.

**Comment by sroot0** [comment]
> @ sroot0，请使用FP16选项。在通常情况下，模型参数将存储在FP16中，但对于包含量化参数的图层，它们将被转换为INT8。顺便说一句，您使用什么OpenVINO版本？

I have another question to ask you. How can I check or verify whether the parameters of the model are quantified to int8?

**Comment by AlexKoff88** [comment]
When exporting the model to ONNX you should find FakeQuantize operations in the model graph which contains quantization parameters. The runtime can interpret these FQs and operations they are connected to as low-precision operations.

**Comment by sroot0** [comment]
> 将模型导出到ONNX时，应在包含量化参数的模型图中找到FakeQuantize操作。运行时可以将这些FQ和它们连接的操作解释为低精度操作。

thank you for your answer , I find FakeQuantize operations in my model .
