### ISSUE TITLE
Error after updating nncf

### ISSUE THREAD

**Issue by sroot0** [openvinotoolkit/nncf_pytorch#217]
When I update nncf, I get an error when I run the previous code，I don’t understand why this error occurs. I am running model d on the GPU.
Traceback (most recent call last):
  File "alexnet.py", line 294, in <module>
    main()
  File "alexnet.py", line 282, in main
    compression_ctrl, model = create_compressed_model(model, nncf_config)
  File "/root/miniconda3/envs/nncf/lib/python3.7/site-packages/nncf-1.4.1-py3.7.egg/nncf/model_creation.py", line 126, in create_compressed_model
    compressed_model = builder.apply_to(compressed_model)
  File "/root/miniconda3/envs/nncf/lib/python3.7/site-packages/nncf-1.4.1-py3.7.egg/nncf/quantization/algo.py", line 170, in apply_to
    insertion_commands = self._quantize_weights(target_model) + self._quantize_activations(target_model)
  File "/root/miniconda3/envs/nncf/lib/python3.7/site-packages/nncf-1.4.1-py3.7.egg/nncf/quantization/algo.py", line 310, in _quantize_weights
    raise RuntimeError(err_msg)
RuntimeError: Quantization parameter constraints specified in NNCF config are incompatible with HW capabilities as specified in HW config type 'CPU'. First conflicting quantizer location: Alexnet/Sequential[features]/NNCFConv2d[0]

**Comment by vshampor** [comment]
@asenina

**Comment by asenina** [comment]
@sroot0  Hi! Please provide your current NNCF config. So far, it looks like you are setting quantizer parameters that are inconsistent with constraints from [hw-config-cpu](https://github.com/openvinotoolkit/nncf_pytorch/blob/develop/nncf/hw_configs/cpu.json). If so, please set `"target_device": "NONE"` in your NNCF config.

**Comment by sroot0** [comment]
> @ sroot0 嗨！请提供您当前的NNCF配置。到目前为止，您似乎正在设置与[hw-config-cpu的](https://github.com/openvinotoolkit/nncf_pytorch/blob/develop/nncf/hw_configs/cpu.json)约束不一致的量化器参数。如果是这样，请`"target_device": "NONE"`在您的NNCF配置中进行设置。

my nncf config is 
![image](https://user-images.githubusercontent.com/50287916/97069379-87431c00-1602-11eb-8812-5ceecc1191aa.png)

**Comment by sroot0** [comment]
> @sroot0 Hi! Please provide your current NNCF config. So far, it looks like you are setting quantizer parameters that are inconsistent with constraints from [hw-config-cpu](https://github.com/openvinotoolkit/nncf_pytorch/blob/develop/nncf/hw_configs/cpu.json). If so, please set `"target_device": "NONE"` in your NNCF config.

thank you for your help
