### ISSUE TITLE
OpenVINO test

### ISSUE THREAD

**Issue by alrzmshy** [openvinotoolkit/nncf_pytorch#47]
Hi,

I managed to take one of the detection models and successfully converted it with the mo_onnx.py (provided by the OpenVino toolkit) to generate the binary and the xml file. However, I have not found any documentation on how to run such models on OpenVino. I have already run models from tensorflow object detection but I'm interested in running your quantized model on OpenVino. So, If you could provide some sample scripts on this, that would be great. Thank you.

**Comment by vshampor** [comment]
Greetings, @alrzmshy!

No specific actions are required to run quantized models on OpenVINO (as opposed to non-quantized models). If you have the .xml and .bin intermediate representation files for your quantized model, you are good to go already - just run it like any other IR vie OpenVINO's Inference Engine (which is not part of this repository - see https://github.com/openvinotoolkit/openvino).

Refer to general OpenVINO Inference Engine documentation for instructions on how to execute the .xml/.bin models with OpenVINO's Inference Engine.
