### ISSUE TITLE
compressed model

### ISSUE THREAD

**Issue by jinqijinqi** [openvinotoolkit/nncf_pytorch#49]
How can get the compressed model and find the compression ratio which is an important concern in deep compression?

**Comment by vshampor** [comment]
Greetings, @jinqijinqi!

@asenina is currently working on analyzing the quantized models and providing certain metrics pertaining to the compression level of a given quantizer layout.

As for other algorithms, check out the implementation of their `.statistics()` methods. These should be implemented namely for sparsity and pruning.
