### ISSUE TITLE
examples/classification　error

### ISSUE THREAD

**Issue by blueskywwc** [openvinotoolkit/nncf_pytorch#69]
Hi,Run the main.py of examples/classification and encountered an error: FileNotFoundError: [Errno 2] No such file or directory:'/home/sky/anaconda3/lib/python3.7/site-packages/nncf-1.3.2- py3.7.egg/nncf/extensions/src/quantization/cpu/functions_cpu.cpp',
How to deal with this error, thank you!

**Comment by vshampor** [comment]
Greetings, @blueskywwc !

Thanks for reporting this, this seems to be an installation process bug. Update the repository to latest develop state, reinstall the nncf package (i.e. `pip uninstall nncf` and then `python setup.py install` and try again?

**Comment by blueskywwc** [comment]
thanks,I will try
