### ISSUE TITLE
Filter prunning for ssd

### ISSUE THREAD

**Issue by sushruthn96** [openvinotoolkit/nncf_pytorch#82]
Is filter prunning supported for SSD based object detection models ?

**Comment by vshampor** [comment]
@sushruthn96, it should be possible to do so - try adapting the available classification filter pruning configs to the SSD training configs (basically just copy and paste `"compression"` sections between the NNCF .json configs).

@mkaglins might correct me if I'm wrong.

**Comment by mkaglins** [comment]
@sushruthn96 @vshampor Yes, filter pruning for SSD models is supported by default with the adapted config.
But unfortunately, export to ONNX for SSD models is not supported yet.
